name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment on changes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (optional, for example, if you're using a build process)
      # - name: Set up Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '14'

      # Step 3: Install dependencies (if you have a package.json)
      # - name: Install dependencies
      #   run: npm install

      # Step 4: Build the project (only if you have a build step)
      # - name: Build project
      #   run: npm run build

      # Step 5: Set up GitHub Pages deployment
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # The branch to deploy to
          folder: ./        # The folder to deploy (use './' to deploy everything in the root)
          token: ${{ secrets.GITHUB_TOKEN }}
